"""
At the command line, only need to run once to install the package via pip:

$ pip install google-generativeai
"""

import google.generativeai as genai

genai.configure(api_key="GOOGLE-API-KEY")

# Set up the model
generation_config = {
  "temperature": 0.9,
  "top_p": 1,
  "top_k": 1,
  "max_output_tokens": 2048,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

model = genai.GenerativeModel(model_name="gemini-pro",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

prompt_parts = [
  "input: le football",
  "output: Le football est un sport",
  "Result ",
  "input: Lionel Messi",
  "output: Lionel Messi est un footballeur",
  "Result ",
  "input: G. Taylor",
  "output: Gareth Taylor",
  "Result ",
  "input: F. Abriel",
  "output: Fabrice Abriel",
  "Result ",
  "input: F. Biancalani",
  "output: Frédéric Biancalani",
  "Result ",
  "input: A. Jonker",
  "output: Andries Jonker",
  "Result ",
  "input: C. Diacre",
  "output: Corinne Diacre",
  "Result ",
  "input: X. Jia",
  "output: Xiuquan Jia",
  "Result ",
  "input: Y. Chandioux",
  "output: Yannick Chandioux",
  "Result ",
  "input: J. Eidevall",
  "output: Jonas Eidevall",
  "Result ",
  "input: P. Lair",
  "output: Patrice Lair",
  "Result ",
  "input: S. Soubeyrand",
  "output: Sandrine Soubeyrand",
  "Result ",
  "input: E. Hayes",
  "output: Emma Hayes",
  "Result ",
  "input: K. Chambers",
  "output: Kelly Chambers",
  "Result ",
  "input: M. Beard",
  "output: Matt Beard",
  "Result ",
  "input: C. Ward",
  "output: Carla Ward",
  "Result ",
  "input: P. Gerhardsson",
  "output: Peter Gerhardsson",
  "Result ",
  "input: D. Ellis",
  "output: Desiree Ellis",
  "Result ",
  "input: M. Bertolini",
  "output: Milena Bertolini",
  "Result ",
  "input: J. Vilda",
  "output: Jorge Vilda",
  "Result ",
  "input: F. Neto",
  "output: Francisco Neto",
  "Result ",
  "input: J. Letelier Henríquez",
  "output: José Antonio Letelier Henríquez",
  "Result ",
  "input: M. Voss-Tecklenburg",
  "output: Martina Voss-Tecklenburg",
  "Result ",
  "input: S. Glotzbach-Wiegman",
  "output: Sarina Glotzbach-Wiegman",
  "Result ",
  "input: S. Bompastor",
  "output: Sonia Bompastor",
  "Result ",
  "input: A. Djeumfa",
  "output: Alain Djeumfa",
  "Result ",
  "input: B. Sorensen",
  "output: Brian Sorensen",
  "Result ",
  "input: T. Halldórsson",
  "output: Thorsteinn Halldórsson",
  "Result ",
  "input: P. Martínez Losa",
  "output: Pedro Martínez Losa",
  "Result ",
  "input: A. Miquel",
  "output: Amandine Miquel",
  "Result ",
  "input: T. Gustavsson",
  "output: Tony Gustavsson",
  "Result ",
  "input: L. Bedford",
  "output: Lydia Bedford",
  "Result ",
  "input: F. Ikeda",
  "output: Futoshi Ikeda",
  "Result ",
  "input: I. Serneels",
  "output: Ives Serneels",
  "Result ",
  "input: V. Andonovski",
  "output: Vlatko Andonovski",
  "Result ",
  "input: H. Riise",
  "output: Hege Riise",
  "Result ",
  "input: C. Bell",
  "output: Colin Bell",
  "Result ",
  "input: N.Kaenson",
  "output: Naruephon Kaenson",
  "Result ",
  "input: B. Priestman",
  "output: Beverly Priestman",
  "Result ",
  "input: Pedro López",
  "output: Pedro López",
  "Result ",
  "input: P. Sundhage",
  "output: Pia Mariane Sundhage",
  "Result ",
  "input: M. Skinner",
  "output: Marc Skinner",
  "Result ",
  "input: R. Skinner",
  "output: Rehanne Skinner",
  "Result ",
  "input: J. Klimkova",
  "output: Jitka Klimkova",
  "Result ",
  "input: O. Harder",
  "output: Olli Harder",
  "Result ",
  "input: R. Waldrum",
  "output: Randy Waldrum",
  "Result ",
  "input: H. Busby",
  "output: Hubert Busby",
  "Result ",
  "input: C. Forest",
  "output: Christophe Forest",
  "Result ",
  "input: G. Portanova",
  "output: Germán Darío Portanova",
  "Result ",
  "input: Q. Shui",
  "output: Qingxia Shui",
  "Result ",
  "input: F. Gonçalves",
  "output: Frédéric Gonçalves",
  "Result ",
  "input: M. Rufié",
  "output: Mathieu Rufié",
  "Result ",
  "input: G. Prêcheur",
  "output: Gérard Prêcheur",
  "Result ",
  "input: M. Bradaia",
  "output: Michel Bradaia",
  "Result ",
  "input: la ligue des champions",
  "output: La Ligue des champions de l'UEFA, également connue sous le nom de Coupe d'Europe des clubs champions, est une compétition annuelle de football de clubs organisée par l'Union des associations européennes de football (UEFA). Elle est considérée comme la compétition de clubs la plus prestigieuse au monde.\n\nLa Ligue des champions est ouverte aux clubs champions des meilleures ligues européennes, ainsi qu'à certains clubs classés deuxième ou troisième dans les ligues les plus fortes. Les clubs se qualifient pour la compétition en fonction de leurs performances dans leurs ligues nationales respectives.\n\nLa Ligue des champions se déroule en deux phases : la phase de groupes et la phase à élimination directe. La phase de groupes est composée de huit groupes de quatre équipes. Chaque équipe affronte les trois autres équipes de son groupe à domicile et à l'extérieur. Les deux meilleures équipes de chaque groupe se qualifient pour la phase à élimination directe.\n\nLa phase à élimination directe est composée de deux tours : les huitièmes de finale, les quarts de finale, les demi-finales et la finale. Les équipes s'affrontent en matchs aller-retour, et l'équipe qui marque le plus de buts sur l'ensemble des deux matchs se qualifie pour le tour suivant. La finale de la Ligue des champions est un événement majeur dans le monde du football, et elle est regardée par des millions de personnes à travers le monde.\n\nLe Real Madrid est le club le plus titré de la Ligue des champions, avec 14 victoires. Le FC Barcelone et l'AC Milan sont les deuxièmes clubs les plus titrés, avec 5 victoires chacun.\n\nLa Ligue des champions est une compétition très disputée et imprévisible, et elle offre toujours des moments forts et des surprises. C'est l'une des compétitions sportives les plus populaires au monde, et elle est suivie par des millions de fans à travers le globe.\n\nVoici quelques faits intéressants sur la Ligue des champions :\n\n* La première édition de la Ligue des champions a eu lieu en 1955-1956.\n* Le Real Madrid est le club le plus titré de la compétition, avec 14 victoires.\n* Le FC Barcelone et l'AC Milan sont les deuxièmes clubs les plus titrés, avec 5 victoires chacun.\n* La finale de la Ligue des champions est l'événement sportif le plus regardé au monde, avec plus de 300 millions de téléspectateurs.\n* Le transfert de joueur le plus cher de l'histoire de la Ligue des champions est celui de Neymar, qui a été transféré du FC Barcelone au Paris Saint-Germain en 2017 pour 222 millions d'euros.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur la Ligue des champions ou sur d'autres sujets.",
  "Result ",
  "input: parle moi du football",
  "output: Le football, également connu sous le nom de soccer dans certains pays, est un sport d'équipe populaire dans le monde entier. Il se joue entre deux équipes de onze joueurs, avec un ballon sphérique. Le but du jeu est de marquer plus de buts que l'équipe adverse en envoyant le ballon dans le filet de l'adversaire.\n\nLe football se joue sur un terrain rectangulaire, appelé terrain de football, qui est divisé en deux moitiés. Chaque moitié est divisée en deux parties, appelées surfaces de réparation. Les joueurs peuvent utiliser leurs pieds, leurs têtes et leur poitrine pour contrôler et passer le ballon. Ils peuvent également tirer au but pour marquer des points.\n\nLe football est un sport très physique et exigeant. Les joueurs doivent être en bonne forme physique et avoir de bonnes compétences techniques. Ils doivent également être capables de travailler en équipe et de communiquer efficacement.\n\nLe football est un sport très populaire et est suivi par des millions de personnes à travers le monde. Il existe de nombreuses ligues de football professionnelles dans le monde, et la Coupe du monde de football est l'événement sportif le plus regardé au monde.\n\nVoici quelques faits intéressants sur le football :\n\n* Le premier match de football enregistré a eu lieu en Écosse en 1872.\n* Le plus grand stade de football du monde est le stade Rungrado May Day en Corée du Nord, qui peut accueillir 150 000 spectateurs.\n* Le joueur de football le plus célèbre de tous les temps est Pelé, qui a remporté trois Coupes du monde avec le Brésil.\n* Le transfert de joueur le plus cher de l'histoire est celui de Neymar, qui a été transféré du FC Barcelone au Paris Saint-Germain en 2017 pour 222 millions d'euros.\n* La Coupe du monde de football est l'événement sportif le plus regardé au monde, avec plus de 3,5 milliards de téléspectateurs en 2018.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: les numéros au football et leurs significations",
  "output: Les numéros au football et leurs significations :\n\n* **Numéro 1** : Gardien de but\n    * Le gardien de but est le seul joueur autorisé à toucher le ballon avec ses mains dans la surface de réparation.\n    * Il est chargé de défendre le but et d'empêcher l'équipe adverse de marquer.\n\n* **Numéro 2** : Arrière droit\n    * L'arrière droit est un défenseur qui joue sur le côté droit du terrain.\n    * Il est chargé de défendre sa zone et d'empêcher l'équipe adverse de progresser sur son côté.\n\n* **Numéro 3** : Arrière gauche\n    * L'arrière gauche est un défenseur qui joue sur le côté gauche du terrain.\n    * Il est chargé de défendre sa zone et d'empêcher l'équipe adverse de progresser sur son côté.\n\n* **Numéro 4** : Milieu de terrain défensif\n    * Le milieu de terrain défensif est un joueur qui joue devant la défense et qui est chargé de protéger la défense et de récupérer le ballon.\n    * Il est souvent le joueur le plus défensif de l'équipe.\n\n* **Numéro 5** : Défenseur central\n    * Le défenseur central est un défenseur qui joue au centre de la défense.\n    * Il est chargé de défendre sa zone et d'empêcher l'équipe adverse de marquer.\n\n* **Numéro 6** : Milieu de terrain central\n    * Le milieu de terrain central est un joueur qui joue au centre du terrain.\n    * Il est chargé de contrôler le jeu et de distribuer le ballon.\n\n* **Numéro 7** : Ailier droit\n    * L'ailier droit est un attaquant qui joue sur le côté droit du terrain.\n    * Il est chargé de créer des occasions de but et de marquer des buts.\n\n* **Numéro 8** : Milieu de terrain offensif\n    * Le milieu de terrain offensif est un joueur qui joue devant le milieu de terrain défensif et qui est chargé de créer des occasions de but et de marquer des buts.\n    * Il est souvent le joueur le plus créatif de l'équipe.\n\n* **Numéro 9** : Avant-centre\n    * L'avant-centre est un attaquant qui joue au centre de l'attaque.\n    * Il est chargé de marquer des buts.\n\n* **Numéro 10** : Meneur de jeu\n    * Le meneur de jeu est un joueur qui joue derrière l'avant-centre et qui est chargé de créer des occasions de but et de marquer des buts.\n    * Il est souvent le joueur le plus technique de l'équipe.\n\n* **Numéro 11** : Ailier gauche\n    * L'ailier gauche est un attaquant qui joue sur le côté gauche du terrain.\n    * Il est chargé de créer des occasions de but et de marquer des buts.\n\nCes numéros ne sont pas attribués de manière fixe aux joueurs, et il existe de nombreuses variations. Par exemple, certains clubs peuvent utiliser le numéro 10 pour un attaquant ou un milieu de terrain offensif, tandis que d'autres peuvent l'utiliser pour un meneur de jeu.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: cite moi 5 joueurs célèbres pour chaque numéro de 1 à 11",
  "output: 5 joueurs célèbres pour chaque numéro de 1 à 11 :\n\n**Numéro 1** : Gardien de but\n\n* Gianluigi Buffon (Italie)\n* Iker Casillas (Espagne)\n* Manuel Neuer (Allemagne)\n* Lev Yashin (Union soviétique)\n* Peter Schmeichel (Danemark)\n\n**Numéro 2** : Arrière droit\n\n* Cafu (Brésil)\n* Dani Alves (Brésil)\n* Philipp Lahm (Allemagne)\n* Javier Zanetti (Argentine)\n* Lilian Thuram (France)\n\n**Numéro 3** : Arrière gauche\n\n* Roberto Carlos (Brésil)\n* Paolo Maldini (Italie)\n* Ashley Cole (Angleterre)\n* Fabio Cannavaro (Italie)\n* Marcelo (Brésil)\n\n**Numéro 4** : Milieu de terrain défensif\n\n* Claude Makélélé (France)\n* Fernando Redondo (Argentine)\n* Sergio Busquets (Espagne)\n* Xabi Alonso (Espagne)\n* Lothar Matthäus (Allemagne)\n\n**Numéro 5** : Défenseur central\n\n* Franz Beckenbauer (Allemagne)\n* Bobby Moore (Angleterre)\n* Rio Ferdinand (Angleterre)\n* Carles Puyol (Espagne)\n* Paolo Maldini (Italie)\n\n**Numéro 6** : Milieu de terrain central\n\n* Xavi Hernández (Espagne)\n* Andrés Iniesta (Espagne)\n* Luka Modrić (Croatie)\n* Toni Kroos (Allemagne)\n* Andrea Pirlo (Italie)\n\n**Numéro 7** : Ailier droit\n\n* Cristiano Ronaldo (Portugal)\n* David Beckham (Angleterre)\n* Luis Figo (Portugal)\n* Garrincha (Brésil)\n* George Best (Irlande du Nord)\n\n**Numéro 8** : Milieu de terrain offensif\n\n* Kaká (Brésil)\n* Zinedine Zidane (France)\n* Ronaldinho (Brésil)\n* Frank Lampard (Angleterre)\n* Steven Gerrard (Angleterre)\n\n**Numéro 9** : Avant-centre\n\n* Lionel Messi (Argentine)\n* Pelé (Brésil)\n* Ronaldo (Brésil)\n* Robert Lewandowski (Pologne)\n* Thierry Henry (France)\n\n**Numéro 10** : Meneur de jeu\n\n* Diego Maradona (Argentine)\n* Pelé (Brésil)\n* Zinedine Zidane (France)\n* Johan Cruyff (Pays-Bas)\n* Michel Platini (France)\n\n**Numéro 11** : Ailier gauche\n\n* Ryan Giggs (Pays de Galles)\n* Arjen Robben (Pays-Bas)\n* Gareth Bale (Pays de Galles)\n* Sadio Mané (Sénégal)\n* Neymar (Brésil)\n\nJ'espère que cette liste te plaît. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: les 20 derniers finales de ligue des champions",
  "output: Voici les 20 dernières finales de la Ligue des champions :\n\n| Année | Vainqueur | Finaliste | Score |\n|---|---|---|---|\n| 2022 | Real Madrid | Liverpool | 1-0 |\n| 2021 | Chelsea | Manchester City | 1-0 |\n| 2020 | Bayern Munich | Paris Saint-Germain | 1-0 |\n| 2019 | Liverpool | Tottenham Hotspur | 2-0 |\n| 2018 | Real Madrid | Liverpool | 3-1 |\n| 2017 | Real Madrid | Juventus | 4-1 |\n| 2016 | Real Madrid | Atlético Madrid | 5-3 (t.a.b.) |\n| 2015 | Barcelone | Juventus | 3-1 |\n| 2014 | Real Madrid | Atlético Madrid | 4-1 (a.p.) |\n| 2013 | Bayern Munich | Borussia Dortmund | 2-1 |\n| 2012 | Chelsea | Bayern Munich | 1-1 (4-3 t.a.b.) |\n| 2011 | Barcelone | Manchester United | 3-1 |\n| 2010 | Inter Milan | Bayern Munich | 2-0 |\n| 2009 | Barcelone | Manchester United | 2-0 |\n| 2008 | Manchester United | Chelsea | 1-1 (6-5 t.a.b.) |\n| 2007 | AC Milan | Liverpool | 2-1 |\n| 2006 | Barcelone | Arsenal | 2-1 |\n| 2005 | Liverpool | AC Milan | 3-3 (3-2 t.a.b.) |\n| 2004 | FC Porto | AS Monaco | 3-0 |\n| 2003 | AC Milan | Juventus | 0-0 (3-2 t.a.b.) |\n\nLe Real Madrid est le club le plus titré de la Ligue des champions, avec 14 victoires. Le FC Barcelone et l'AC Milan sont les deuxièmes clubs les plus titrés, avec 5 victoires chacun.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: la premier league",
  "output: La Premier League est le championnat de football professionnel de première division en Angleterre. Elle est considérée comme l'une des ligues de football les plus compétitives et les plus populaires au monde.\n\nLa Premier League a été créée en 1992, suite à la décision des clubs de première division de se séparer de la Football League First Division. La nouvelle ligue a été créée dans le but d'augmenter les revenus de la télévision et de rendre le football anglais plus compétitif sur la scène européenne.\n\nLa Premier League est composée de 20 clubs, qui s'affrontent en matchs aller-retour tout au long de la saison. Chaque club joue 38 matchs, pour un total de 380 matchs par saison. L'équipe qui termine en tête du classement à la fin de la saison est sacrée championne d'Angleterre.\n\nLes quatre premières équipes du classement se qualifient pour la Ligue des champions, la compétition de clubs la plus prestigieuse au monde. Les équipes classées de la cinquième à la septième place se qualifient pour la Ligue Europa, la deuxième compétition européenne la plus importante.\n\nLa Premier League est une ligue très",
  "Result ",
  "input: les meilleurs buteurs de l'histoire de la première league",
  "output: Voici les meilleurs buteurs de l'histoire de la Premier League :\n\n| Rang | Joueur | Buts |\n|---|---|---|\n| 1 | Alan Shearer | 260 |\n| 2 | Wayne Rooney | 208 |\n| 3 | Andrew Cole | 187 |\n| 4 | Sergio Agüero | 184 |\n| 5 | Thierry Henry | 175 |\n| 6 | Frank Lampard | 177 |\n| 7 | Robbie Fowler | 163 |\n| 8 | Jermain Defoe | 162 |\n| 9 | Michael Owen | 150 |\n| 10 | Les Ferdinand | 149 |\n\nAlan Shearer est le meilleur buteur de l'histoire de la Premier League, avec 260 buts marqués en 441 matchs. Il a joué pour Blackburn Rovers et Newcastle United.\n\nWayne Rooney est le deuxième meilleur buteur de l'histoire de la Premier League, avec 208 buts marqués en 491 matchs. Il a joué pour Everton et Manchester United.\n\nAndrew Cole est le troisième meilleur buteur de l'histoire de la Premier League, avec 187 buts marqués en 414 matchs. Il a joué pour Newcastle United, Manchester United et Blackburn Rovers.\n\nSergio Agüero est le quatrième meilleur buteur de l'histoire de la Premier League, avec 184 buts marqués en 275 matchs. Il a joué pour Manchester City.\n\nThierry Henry est le cinquième meilleur buteur de l'histoire de la Premier League, avec 175 buts marqués en 258 matchs. Il a joué pour Arsenal.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: les 20 derniers champions de premier league",
  "output: Voici les 20 derniers champions de Premier League :\n\n* 2022/2023 : Manchester City\n* 2021/2022 : Manchester City\n* 2020/2021 : Manchester City\n* 2019/2020 : Liverpool\n* 2018/2019 : Manchester City\n* 2017/2018 : Manchester City\n* 2016/2017 : Chelsea\n* 2015/2016 : Leicester City\n* 2014/2015 : Chelsea\n* 2013/2014 : Manchester City\n* 2012/2013 : Manchester United\n* 2011/2012 : Manchester City\n* 2010/2011 : Manchester United\n* 2009/2010 : Chelsea\n* 2008/2009 : Manchester United\n* 2007/2008 : Manchester United\n* 2006/2007 : Manchester United\n* 2005/2006 : Chelsea\n* 2004/2005 : Chelsea\n* 2003/2004 : Arsenal\n\nManchester City est le club le plus titré de Premier League ces dernières années, avec 6 victoires au cours des 10 dernières saisons. Manchester United est le deuxième club le plus titré, avec 13 victoires au total. Chelsea est le troisième club le plus titré, avec 5 victoires.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: la liga",
  "output: La Liga, également connue sous le nom de Primera División, est la première division du championnat espagnol de football. Elle est considérée comme l'une des ligues de football les plus prestigieuses et les plus compétitives au monde.\n\nLa Liga est composée de 20 équipes, qui s'affrontent en matchs aller-retour sur une saison régulière de 38 journées. Les quatre premières équipes du classement se qualifient pour la Ligue des champions, tandis que les équipes classées de la cinquième à la septième place se qualifient pour la Ligue Europa. Les trois dernières équipes du classement sont reléguées en Segunda División, la deuxième division espagnole.\n\nLes deux clubs les plus titrés de la Liga sont le Real Madrid et le FC Barcelone, qui se partagent la majorité des titres depuis la création de la compétition en 1929. D'autres clubs ont également remporté le titre, notamment l'Atlético Madrid, Valence CF et le Deportivo La Corogne.\n\nLa Liga est réputée pour son style de jeu offensif et spectaculaire, avec de nombreux buts et des matchs passionnants. Elle est également connue pour ses grands stades et son atmosphère électrique.\n\nVoici quelques faits intéressants sur la Liga :\n\n* La Liga est la première division du championnat espagnol de football.\n* Elle est composée de 20 équipes, qui s'affrontent en matchs aller-retour sur une saison régulière de 38 journées.\n* Les quatre premières équipes du classement se qualifient pour la Ligue des champions, tandis que les équipes classées de la cinquième à la septième place se qualifient pour la Ligue Europa.\n* Les trois dernières équipes du classement sont reléguées en Segunda División, la deuxième division espagnole.\n* Le Real Madrid et le FC Barcelone sont les deux clubs les plus titrés de la Liga, avec 35 et 26 titres respectivement.\n* La Liga est réputée pour son style de jeu offensif et spectaculaire, avec de nombreux buts et des matchs passionnants.\n* Elle est également connue pour ses grands stades et son atmosphère électrique.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur la Liga ou sur d'autres sujets.",
  "Result ",
  "input: les meilleurs buteurs de l'histoire de la liga",
  "output: Voici les meilleurs buteurs de l'histoire de la Liga :\n\n| Rang | Joueur | Buts |\n|---|---|---|\n| 1 | Lionel Messi | 474 |\n| 2 | Cristiano Ronaldo | 311 |\n| 3 | Telmo Zarra | 251 |\n| 4 | Raúl González | 228 |\n| 5 | Alfredo Di Stéfano | 227 |\n| 6 | Hugo Sánchez | 208 |\n| 7 | César Rodríguez | 190 |\n| 8 | Pahiño | 188 |\n| 9 | Carlos Alonso González | 186 |\n| 10 | Juan Arza | 182 |\n\nLionel Messi est le meilleur buteur de l'histoire de la Liga, avec 474 buts marqués en 520 matchs. Il est également le meilleur buteur de l'histoire du FC Barcelone, avec 672 buts marqués en 778 matchs.\n\nCristiano Ronaldo est le deuxième meilleur buteur de l'histoire de la Liga, avec 311 buts marqués en 292 matchs. Il est également le meilleur buteur de l'histoire du Real Madrid, avec 450 buts marqués en 438 matchs.\n\nTelmo Zarra est le troisième meilleur buteur de l'histoire de la Liga, avec 251 buts marqués en 278 matchs. Il est également le meilleur buteur de l'histoire de l'Athletic Bilbao, avec 335 buts marqués en 352 matchs.\n\nRaúl González est le quatrième meilleur buteur de l'histoire de la Liga, avec 228 buts marqués en 550 matchs. Il est également le meilleur buteur de l'histoire du Real Madrid, avec 323 buts marqués en 741 matchs.\n\nAlfredo Di Stéfano est le cinquième meilleur buteur de l'histoire de la Liga, avec 227 buts marqués en 329 matchs. Il est également le meilleur buteur de l'histoire du Real Madrid, avec 307 buts marqués en 396 matchs.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: les 20 derniers vainqueurs de la liga",
  "output: Voici les 20 derniers vainqueurs de la Liga :\n\n* 2022/2023 : FC Barcelone\n* 2021/2022 : Real Madrid\n* 2020/2021 : Atlético Madrid\n* 2019/2020 : Real Madrid\n* 2018/2019 : FC Barcelone\n* 2017/2018 : FC Barcelone\n* 2016/2017 : Real Madrid\n* 2015/2016 : FC Barcelone\n* 2014/2015 : FC Barcelone\n* 2013/2014 : Atlético Madrid\n* 2012/2013 : FC Barcelone\n* 2011/2012 : Real Madrid\n* 2010/2011 : FC Barcelone\n* 2009/2010 : FC Barcelone\n* 2008/2009 : FC Barcelone\n* 2007/2008 : Real Madrid\n* 2006/2007 : Real Madrid\n* 2005/2006 : FC Barcelone\n* 2004/2005 : FC Barcelone\n* 2003/2004 : Valence CF\n\nLe FC Barcelone est le club le plus titré de la Liga ces dernières années, avec 9 victoires au cours des 20 dernières saisons. Le Real Madrid est le deuxième club le plus titré, avec 8 victoires. L'Atlético Madrid est le troisième club le plus titré, avec 2 victoires.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: les meilleurs buteurs de l'histoire de la liga",
  "output: Voici les meilleurs buteurs de l'histoire de la Liga :\n\n| Rang | Joueur | Buts |\n|---|---|---|\n| 1 | Lionel Messi | 474 |\n| 2 | Cristiano Ronaldo | 311 |\n| 3 | Telmo Zarra | 251 |\n| 4 | Raúl González | 228 |\n| 5 | Alfredo Di Stéfano | 227 |\n| 6 | Hugo Sánchez | 208 |\n| 7 | César Rodríguez | 190 |\n| 8 | Pahiño | 188 |\n| 9 | Carlos Alonso González | 186 |\n| 10 | Juan Arza | 182 |\n\nLionel Messi est le meilleur buteur de l'histoire de la Liga, avec 474 buts marqués en 520 matchs. Il est également le meilleur buteur de l'histoire du FC Barcelone, avec 672 buts marqués en 778 matchs.\n\nCristiano Ronaldo est le deuxième meilleur buteur de l'histoire de la Liga, avec 311 buts marqués en 292 matchs. Il est également le meilleur buteur de l'histoire du Real Madrid, avec 450 buts marqués en 438 matchs.\n\nTelmo Zarra est le troisième meilleur buteur de l'histoire de la Liga, avec 251 buts marqués en 278 matchs. Il est également le meilleur buteur de l'histoire de l'Athletic Bilbao, avec 335 buts marqués en 352 matchs.\n\nRaúl González est le quatrième meilleur buteur de l'histoire de la Liga, avec 228 buts marqués en 550 matchs. Il est également le meilleur buteur de l'histoire du Real Madrid, avec 323 buts marqués en 741 matchs.\n\nAlfredo Di Stéfano est le cinquième meilleur buteur de l'histoire de la Liga, avec 227 buts marqués en 329 matchs. Il est également le meilleur buteur de l'histoire du Real Madrid, avec 307 buts marqués en 396 matchs.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: la bundesliga",
  "output: La Bundesliga est le championnat de football professionnel de première division en Allemagne. Elle est considérée comme l'une des ligues de football les plus compétitives et les plus populaires au monde.\n\nLa Bundesliga a été créée en 1963, suite à la décision de la Fédération allemande de football (DFB) de créer une ligue nationale unique. La ligue est composée de 18 équipes, qui s'affrontent en matchs aller-retour sur une saison régulière de 34 journées. Les quatre premières équipes du classement se qualifient pour la Ligue des champions, tandis que les équipes classées de la cinquième à la septième place se qualifient pour la Ligue Europa. Les deux dernières équipes du classement sont reléguées en 2. Bundesliga, la deuxième division allemande.\n\nLes clubs les plus titrés de la Bundesliga sont le Bayern Munich, le Borussia Dortmund et le Hambourg SV. Le Bayern Munich est de loin le club le plus titré, avec 31 titres de champion d'Allemagne.\n\nLa Bundesliga est réputée pour son style de jeu rapide et offensif, avec de nombreux buts et des matchs passionnants. Elle est également connue pour ses grands stades et son atmosphère électrique.\n\nVoici quelques faits intéressants sur la Bundesliga :\n\n* La Bundesliga est le championnat de football professionnel de première division en Allemagne.\n* Elle a été créée en 1963.\n* La ligue est composée de 18 équipes, qui s'affrontent en matchs aller-retour sur une saison régulière de 34 journées.\n* Les quatre premières équipes du classement se qualifient pour la Ligue des champions, tandis que les équipes classées de la cinquième à la septième place se qualifient pour la Ligue Europa.\n* Les deux dernières équipes du classement sont reléguées en 2. Bundesliga, la deuxième division allemande.\n* Le Bayern Munich est le club le plus titré de la Bundesliga, avec 31 titres de champion d'Allemagne.\n* La Bundesliga est réputée pour son style de jeu rapide et offensif, avec de nombreux buts et des matchs passionnants.\n* Elle est également connue pour ses grands stades et son atmosphère électrique.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur la Bundesliga ou sur d'autres sujets.",
  "Result ",
  "input: les 20 derniers vainqueurs de bundesliga",
  "output: Voici les 20 derniers vainqueurs de la Bundesliga :\n\n* 2022/2023 : Bayern Munich\n* 2021/2022 : Bayern Munich\n* 2020/2021 : Bayern Munich\n* 2019/2020 : Bayern Munich\n* 2018/2019 : Bayern Munich\n* 2017/2018 : Bayern Munich\n* 2016/2017 : Bayern Munich\n* 2015/2016 : Bayern Munich\n* 2014/2015 : Bayern Munich\n* 2013/2014 : Bayern Munich\n* 2012/2013 : Bayern Munich\n* 2011/2012 : Borussia Dortmund\n* 2010/2011 : Borussia Dortmund\n* 2009/2010 : Bayern Munich\n* 2008/2009 : VfL Wolfsburg\n* 2007/2008 : Bayern Munich\n* 2006/2007 : VfB Stuttgart\n* 2005/2006 : Bayern Munich\n* 2004/2005 : Bayern Munich\n* 2003/2004 : Werder Brême\n\nLe Bayern Munich est le club le plus titré de la Bundesliga, avec 32 victoires au cours des 20 dernières saisons. Le Borussia Dortmund est le deuxième club le plus titré, avec 8 victoires. Le VfB Stuttgart et le VfL Wolfsburg ont chacun remporté le titre une fois au cours des 20 dernières saisons.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: les meilleirs buteurs de l'histoir de la bundesliga",
  "output: Voici les meilleurs buteurs de l'histoire de la Bundesliga :\n\n| Rang | Joueur | Buts |\n|---|---|---|\n| 1 | Gerd Müller | 365 |\n| 2 | Robert Lewandowski | 312 |\n| 3 | Klaus Fischer | 268 |\n| 4 | Jupp Heynckes | 220 |\n| 5 | Manfred Burgsmüller | 213 |\n| 6 | Uwe Seeler | 207 |\n| 7 | Claudio Pizarro | 197 |\n| 8 | Stefan Kuntz | 179 |\n| 9 | Dieter Müller | 177 |\n| 10 | Ulf Kirsten | 173 |\n\nGerd Müller est le meilleur buteur de l'histoire de la Bundesliga, avec 365 buts marqués en 427 matchs. Il a joué pour le Bayern Munich de 1964 à 1979 et est considéré comme l'un des meilleurs attaquants de tous les temps.\n\nRobert Lewandowski est le deuxième meilleur buteur de l'histoire de la Bundesliga, avec 312 buts marqués en 382 matchs. Il joue pour le Bayern Munich depuis 2014 et est l'un des meilleurs attaquants du monde.\n\nKlaus Fischer est le troisième meilleur buteur de l'histoire de la Bundesliga, avec 268 buts marqués en 535 matchs. Il a joué pour le TSV 1860 Munich, le FC Cologne, le Schalke 04 et le VfL Bochum de 1968 à 1988.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: la serie A",
  "output: La Serie A est le championnat de football professionnel de première division en Italie. Elle est considérée comme l'une des ligues de football les plus compétitives et les plus populaires au monde.\n\nLa Serie A a été créée en 1898, ce qui en fait l'une des plus anciennes ligues de football au monde. Elle est composée de 20 équipes, qui s'affrontent en matchs aller-retour sur une saison régulière de 38 journées. Les quatre premières équipes du classement se qualifient pour la Ligue des champions, tandis que les équipes classées de la cinquième à la septième place se qualifient pour la Ligue Europa. Les trois dernières équipes du classement sont reléguées en Serie B, la deuxième division italienne.\n\nLes clubs les plus titrés de la Serie A sont la Juventus, l'AC Milan et l'Inter Milan. La Juventus est de loin le club le plus titré, avec 36 titres de champion d'Italie.\n\nLa Serie A est réputée pour son style de jeu défensif et tactique, avec beaucoup de passes courtes et d'occasions de but créées par des joueurs talentueux. Elle est également connue pour ses grands stades et son atmosphère électrique.\n\nVoici quelques faits intéressants sur la Serie A :\n\n* La Serie A est le championnat de football professionnel de première division en Italie.\n* Elle a été créée en 1898.\n* La ligue est composée de 20 équipes, qui s'affrontent en matchs aller-retour sur une saison régulière de 38 journées.\n* Les quatre premières équipes du classement se qualifient pour la Ligue des champions, tandis que les équipes classées de la cinquième à la septième place se qualifient pour la Ligue Europa.\n* Les trois dernières équipes du classement sont reléguées en Serie B, la deuxième division italienne.\n* La Juventus est le club le plus titré de la Serie A, avec 36 titres de champion d'Italie.\n* La Serie A est réputée pour son style de jeu défensif et tactique, avec beaucoup de passes courtes et d'occasions de but créées par des joueurs talentueux.\n* Elle est également connue pour ses grands stades et son atmosphère électrique.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur la Serie A ou sur d'autres sujets.",
  "Result ",
  "input: les 20 derniers vainqueurs de Serie A",
  "output: Voici les 20 derniers vainqueurs de la Serie A :\n\n* 2022/2023 : AC Milan\n* 2021/2022 : AC Milan\n* 2020/2021 : Inter Milan\n* 2019/2020 : Juventus\n* 2018/2019 : Juventus\n* 2017/2018 : Juventus\n* 2016/2017 : Juventus\n* 2015/2016 : Juventus\n* 2014/2015 : Juventus\n* 2013/2014 : Juventus\n* 2012/2013 : Juventus\n* 2011/2012 : Juventus\n* 2010/2011 : AC Milan\n* 2009/2010 : Inter Milan\n* 2008/2009 : Inter Milan\n* 2007/2008 : Inter Milan\n* 2006/2007 : Inter Milan\n* 2005/2006 : Inter Milan\n* 2004/2005 : Juventus\n* 2003/2004 : AC Milan\n\nLa Juventus est le club le plus titré de la Serie A, avec 36 victoires au cours des 20 dernières saisons. L'Inter Milan est le deuxième club le plus titré, avec 19 victoires. L'AC Milan est le troisième club le plus titré, avec 19 victoires.\n\nJ'espère que ces informations t'ont été utiles. N'hésite pas à me poser d'autres questions sur le football ou sur d'autres sujets.",
  "Result ",
  "input: 9/5/04",
  "output: Girona FC",
  "Result 1:2",
  "input: 9/18/04",
  "output: RCD Espanyol B",
  "Result 2:0",
  "input: 10/31/04",
  "output: Villajoyosa CF",
  "Result 2:1",
  "input: 11/28/04",
  "output: UE Figueres",
  "Result 2:2",
  "input: 12/19/04",
  "output: CD Alcoyano",
  "Result 2:0",
  "input: 4/23/05",
  "output: UE Figueres",
  "Result 2:2",
  "input: 5/1/05",
  "output: Albacete Balompié",
  "Result 2:0",
  "input: 11/2/05",
  "output: Panathinaikos Athens",
  "Result 5:0",
  "input: 11/27/05",
  "output: Racing Santander",
  "Result 4:1",
  "input: 1/15/06",
  "output: Athletic Bilbao",
  "Result 2:1",
  "input: 1/22/06",
  "output: Deportivo Alavés",
  "Result 2:0",
  "input: 1/29/06",
  "output: RCD Mallorca",
  "Result 0:3",
  "input: 1/29/06",
  "output: RCD Mallorca",
  "Result 0:3",
  "input: 2/1/06",
  "output: Real Zaragoza",
  "Result 2:1",
  "input: 2/18/06",
  "output: Real Betis Balompié",
  "Result 5:1",
  "input: 8/28/06",
  "output: Celta de Vigo",
  "Result 2:3",
  "input: 9/9/06",
  "output: CA Osasuna",
  "Result 3:0",
  "input: 9/27/06",
  "output: SV Werder Bremen",
  "Result 1:1",
  "input: 10/15/06",
  "output: Sevilla FC",
  "Result 3:1",
  "input: 3/10/07",
  "output: Real Madrid",
  "Result 3:3",
  "input: 3/10/07",
  "output: Real Madrid",
  "Result 3:3",
  "input: 3/10/07",
  "output: Real Madrid",
  "Result 3:3",
  "input: 3/17/07",
  "output: Recreativo Huelva",
  "Result 0:4",
  "input: 3/31/07",
  "output: Deportivo de La Coruña",
  "Result 2:1",
  "input: 4/18/07",
  "output: Getafe CF",
  "Result 5:2",
  "input: 4/18/07",
  "output: Getafe CF",
  "Result 5:2",
  "input: 5/20/07",
  "output: Atlético de Madrid",
  "Result 0:6",
  "input: 5/20/07",
  "output: Atlético de Madrid",
  "Result 0:6",
  "input: 6/9/07",
  "output: RCD Espanyol Barcelona",
  "Result 2:2",
  "input: 6/9/07",
  "output: RCD Espanyol Barcelona",
  "Result 2:2",
  "input: 6/17/07",
  "output: Gimnàstic de Tarragona",
  "Result 1:5",
  "input: 6/17/07",
  "output: Gimnàstic de Tarragona",
  "Result 1:5",
  "input: 9/19/07",
  "output: Olympique Lyon",
  "Result 3:0",
  "input: 9/22/07",
  "output: Sevilla FC",
  "Result 2:1",
  "input: 9/22/07",
  "output: Sevilla FC",
  "Result 2:1",
  "input: 9/26/07",
  "output: Real Zaragoza",
  "Result 4:1",
  "input: 9/26/07",
  "output: Real Zaragoza",
  "Result 4:1",
  "input: 9/29/07",
  "output: Levante UD",
  "Result 1:4",
  "input: 10/2/07",
  "output: VfB Stuttgart",
  "Result 0:2",
  "input: 10/7/07",
  "output: Atlético de Madrid",
  "Result 3:0",
  "input: 10/28/07",
  "output: UD Almería",
  "Result 2:0",
  "input: 11/7/07",
  "output: Rangers FC",
  "Result 2:0",
  "input: 11/24/07",
  "output: Recreativo Huelva",
  "Result 3:0",
  "input: 11/27/07",
  "output: Olympique Lyon",
  "Result 2:2",
  "input: 2/20/08",
  "output: Celtic FC",
  "Result 2:3",
  "input: 2/20/08",
  "output: Celtic FC",
  "Result 2:3",
  "input: 2/24/08",
  "output: Levante UD",
  "Result 5:1",
  "input: 5/4/08",
  "output: Valencia CF",
  "Result 6:0",
  "input: 9/13/08",
  "output: Racing Santander",
  "Result 1:1",
  "input: 9/21/08",
  "output: Sporting Gijón",
  "Result 1:6",
  "input: 9/21/08",
  "output: Sporting Gijón",
  "Result 1:6",
  "input: 9/27/08",
  "output: RCD Espanyol Barcelona",
  "Result 1:2",
  "input: 10/1/08",
  "output: Shakhtar Donetsk",
  "Result 1:2",
  "input: 10/1/08",
  "output: Shakhtar Donetsk",
  "Result 1:2",
  "input: 10/4/08",
  "output: Atlético de Madrid",
  "Result 6:1",
  "input: 10/22/08",
  "output: FC Basel 1893",
  "Result 0:5",
  "input: 11/1/08",
  "output: Málaga CF",
  "Result 1:4",
  "input: 11/4/08",
  "output: FC Basel 1893",
  "Result 1:1",
  "input: 11/12/08",
  "output: Benidorm CD",
  "Result 1:0",
  "input: 11/16/08",
  "output: Recreativo Huelva",
  "Result 0:2",
  "input: 11/26/08",
  "output: Sporting CP",
  "Result 2:5",
  "input: 11/29/08",
  "output: Sevilla FC",
  "Result 0:3",
  "input: 11/29/08",
  "output: Sevilla FC",
  "Result 0:3",
  "input: 12/13/08",
  "output: Real Madrid",
  "Result 2:0",
  "input: 1/6/09",
  "output: Atlético de Madrid",
  "Result 1:3",
  "input: 1/6/09",
  "output: Atlético de Madrid",
  "Result 1:3",
  "input: 1/6/09",
  "output: Atlético de Madrid",
  "Result 1:3",
  "input: 1/11/09",
  "output: CA Osasuna",
  "Result 2:3",
  "input: 1/17/09",
  "output: Deportivo de La Coruña",
  "Result 5:0",
  "input: 1/24/09",
  "output: CD Numancia",
  "Result 4:1",
  "input: 1/24/09",
  "output: CD Numancia",
  "Result 4:1",
  "input: 2/1/09",
  "output: Racing Santander",
  "Result 1:2",
  "input: 2/1/09",
  "output: Racing Santander",
  "Result 1:2",
  "input: 3/1/09",
  "output: Atlético de Madrid",
  "Result 4:3",
  "input: 3/4/09",
  "output: RCD Mallorca",
  "Result 1:1",
  "input: 3/7/09",
  "output: Athletic Bilbao",
  "Result 2:0",
  "input: 3/11/09",
  "output: Olympique Lyon",
  "Result 5:2",
  "input: 3/22/09",
  "output: Málaga CF",
  "Result 6:0",
  "input: 4/8/09",
  "output: Bayern Munich",
  "Result 4:0",
  "input: 4/8/09",
  "output: Bayern Munich",
  "Result 4:0",
  "input: 4/18/09",
  "output: Getafe CF",
  "Result 0:1",
  "input: 4/25/09",
  "output: Valencia CF",
  "Result 2:2",
  "input: 5/2/09",
  "output: Real Madrid",
  "Result 2:6",
  "input: 5/2/09",
  "output: Real Madrid",
  "Result 2:6",
  "input: 5/13/09",
  "output: Athletic Bilbao",
  "Result 4:1",
  "input: 5/27/09",
  "output: Manchester United",
  "Result 2:0",
  "input: 8/23/09",
  "output: Athletic Bilbao",
  "Result 3:0",
  "input: 8/23/09",
  "output: Athletic Bilbao",
  "Result 3:0",
  "input: 9/12/09",
  "output: Getafe CF",
  "Result 0:2",
  "input: 9/19/09",
  "output: Atlético de Madrid",
  "Result 5:2",
  "input: 9/19/09",
  "output: Atlético de Madrid",
  "Result 5:2",
  "input: 9/22/09",
  "output: Racing Santander",
  "Result 1:4",
  "input: 9/22/09",
  "output: Racing Santander",
  "Result 1:4",
  "input: 9/29/09",
  "output: Dynamo Kyiv",
  "Result 2:0",
  "input: 10/25/09",
  "output: Real Zaragoza",
  "Result 6:1",
  "input: 11/7/09",
  "output: RCD Mallorca",
  "Result 4:2",
  "input: 11/10/09",
  "output: Cultural Leonesa",
  "Result 5:0",
  "input: 12/5/09",
  "output: Deportivo de La Coruña",
  "Result 1:3",
  "input: 12/5/09",
  "output: Deportivo de La Coruña",
  "Result 1:3",
  "input: 12/9/09",
  "output: Dynamo Kyiv",
  "Result 1:2",
  "input: 12/16/09",
  "output: CF Atlante",
  "Result 1:3",
  "input: 12/19/09",
  "output: Club Estudiantes de La Plata",
  "Result 1:2",
  "input: 1/10/10",
  "output: CD Tenerife",
  "Result 0:5",
  "input: 1/10/10",
  "output: CD Tenerife",
  "Result 0:5",
  "input: 1/10/10",
  "output: CD Tenerife",
  "Result 0:5",
  "input: 1/16/10",
  "output: Sevilla FC",
  "Result 4:0",
  "input: 1/16/10",
  "output: Sevilla FC",
  "Result 4:0",
  "input: 1/23/10",
  "output: Real Valladolid CF",
  "Result 0:3",
  "input: 2/6/10",
  "output: Getafe CF",
  "Result 2:1",
  "input: 2/27/10",
  "output: Málaga CF",
  "Result 2:1",
  "input: 3/6/10",
  "output: UD Almería",
  "Result 2:2",
  "input: 3/6/10",
  "output: UD Almería",
  "Result 2:2",
  "input: 3/14/10",
  "output: Valencia CF",
  "Result 3:0",
  "input: 3/14/10",
  "output: Valencia CF",
  "Result 3:0",
  "input: 3/14/10",
  "output: Valencia CF",
  "Result 3:0",
  "input: 3/17/10",
  "output: VfB Stuttgart",
  "Result 4:0",
  "input: 3/17/10",
  "output: VfB Stuttgart",
  "Result 4:0",
  "input: 3/21/10",
  "output: Real Zaragoza",
  "Result 2:4",
  "input: 3/21/10",
  "output: Real Zaragoza",
  "Result 2:4",
  "input: 3/21/10",
  "output: Real Zaragoza",
  "Result 2:4",
  "input: 4/3/10",
  "output: Athletic Bilbao",
  "Result 4:1",
  "input: 4/6/10",
  "output: Arsenal FC",
  "Result 4:1",
  "input: 4/6/10",
  "output: Arsenal FC",
  "Result 4:1",
  "input: 4/6/10",
  "output: Arsenal FC",
  "Result 4:1",
  "input: 4/6/10",
  "output: Arsenal FC",
  "Result 4:1",
  "input: 4/10/10",
  "output: Real Madrid",
  "Result 0:2",
  "input: 5/1/10",
  "output: Villarreal CF",
  "Result 1:4",
  "input: 5/1/10",
  "output: Villarreal CF",
  "Result 1:4",
  "input: 5/4/10",
  "output: CD Tenerife",
  "Result 4:1",
  "input: 5/4/10",
  "output: CD Tenerife",
  "Result 4:1",
  "input: 5/8/10",
  "output: Sevilla FC",
  "Result 2:3",
  "input: 5/16/10",
  "output: Real Valladolid CF",
  "Result 4:0",
  "input: 5/16/10",
  "output: Real Valladolid CF",
  "Result 4:0",
  "input: 8/21/10",
  "output: Sevilla FC",
  "Result 4:0",
  "input: 8/21/10",
  "output: Sevilla FC",
  "Result 4:0",
  "input: 8/21/10",
  "output: Sevilla FC",
  "Result 4:0",
  "input: 8/29/10",
  "output: Racing Santander",
  "Result 0:3",
  "input: 9/14/10",
  "output: Panathinaikos Athens",
  "Result 5:1",
  "input: 9/14/10",
  "output: Panathinaikos Athens",
  "Result 5:1",
  "input: 9/19/10",
  "output: Atlético de Madrid",
  "Result 1:2",
  "input: 10/3/10",
  "output: RCD Mallorca",
  "Result 1:1",
  "input: 10/20/10",
  "output: FC Copenhagen",
  "Result 2:0",
  "input: 10/20/10",
  "output: FC Copenhagen",
  "Result 2:0",
  "input: 10/23/10",
  "output: Real Zaragoza",
  "Result 0:2",
  "input: 10/23/10",
  "output: Real Zaragoza",
  "Result 0:2",
  "input: 10/30/10",
  "output: Sevilla FC",
  "Result 5:0",
  "input: 10/30/10",
  "output: Sevilla FC",
  "Result 5:0",
  "input: 11/2/10",
  "output: FC Copenhagen",
  "Result 1:1",
  "input: 11/7/10",
  "output: Getafe CF",
  "Result 1:3",
  "input: 11/10/10",
  "output: Club Atlético de Ceuta",
  "Result 5:1",
  "input: 11/13/10",
  "output: Villarreal CF",
  "Result 3:1",
  "input: 11/13/10",
  "output: Villarreal CF",
  "Result 3:1",
  "input: 11/20/10",
  "output: UD Almería",
  "Result 0:8",
  "input: 11/20/10",
  "output: UD Almería",
  "Result 0:8",
  "input: 11/20/10",
  "output: UD Almería",
  "Result 0:8",
  "input: 11/24/10",
  "output: Panathinaikos Athens",
  "Result 0:3",
  "input: 12/4/10",
  "output: CA Osasuna",
  "Result 0:3",
  "input: 12/4/10",
  "output: CA Osasuna",
  "Result 0:3",
  "input: 12/12/10",
  "output: Real Sociedad",
  "Result 5:0",
  "input: 12/12/10",
  "output: Real Sociedad",
  "Result 5:0",
  "input: 1/8/11",
  "output: Deportivo de La Coruña",
  "Result 0:4",
  "input: 1/12/11",
  "output: Real Betis Balompié",
  "Result 5:0",
  "input: 1/12/11",
  "output: Real Betis Balompié",
  "Result 5:0",
  "input: 1/12/11",
  "output: Real Betis Balompié",
  "Result 5:0",
  "input: 1/19/11",
  "output: Real Betis Balompié",
  "Result 3:1",
  "input: 1/22/11",
  "output: Racing Santander",
  "Result 3:0",
  "input: 1/26/11",
  "output: UD Almería",
  "Result 5:0",
  "input: 1/26/11",
  "output: UD Almería",
  "Result 5:0",
  "input: 1/29/11",
  "output: Hércules CF",
  "Result 0:3",
  "input: 1/29/11",
  "output: Hércules CF",
  "Result 0:3",
  "input: 2/5/11",
  "output: Atlético de Madrid",
  "Result 3:0",
  "input: 2/5/11",
  "output: Atlético de Madrid",
  "Result 3:0",
  "input: 2/5/11",
  "output: Atlético de Madrid",
  "Result 3:0",
  "input: 2/20/11",
  "output: Athletic Bilbao",
  "Result 2:1",
  "input: 2/26/11",
  "output: RCD Mallorca",
  "Result 0:3",
  "input: 3/2/11",
  "output: Valencia CF",
  "Result 0:1",
  "input: 3/8/11",
  "output: Arsenal FC",
  "Result 3:1",
  "input: 3/8/11",
  "output: Arsenal FC",
  "Result 3:1",
  "input: 4/9/11",
  "output: UD Almería",
  "Result 3:1",
  "input: 4/9/11",
  "output: UD Almería",
  "Result 3:1",
  "input: 4/12/11",
  "output: Shakhtar Donetsk",
  "Result 0:1",
  "input: 4/16/11",
  "output: Real Madrid",
  "Result 1:1",
  "input: 4/23/11",
  "output: CA Osasuna",
  "Result 2:0",
  "input: 4/27/11",
  "output: Real Madrid",
  "Result 0:2",
  "input: 4/27/11",
  "output: Real Madrid",
  "Result 0:2",
  "input: 5/28/11",
  "output: Manchester United",
  "Result 3:1",
  "input: 8/14/11",
  "output: Real Madrid",
  "Result 2:2",
  "input: 8/17/11",
  "output: Real Madrid",
  "Result 3:2",
  "input: 8/17/11",
  "output: Real Madrid",
  "Result 3:2",
  "input: 8/26/11",
  "output: FC Porto",
  "Result 2:0",
  "input: 8/29/11",
  "output: Villarreal CF",
  "Result 5:0",
  "input: 8/29/11",
  "output: Villarreal CF",
  "Result 5:0",
  "input: 9/17/11",
  "output: CA Osasuna",
  "Result 8:0",
  "input: 9/17/11",
  "output: CA Osasuna",
  "Result 8:0",
  "input: 9/17/11",
  "output: CA Osasuna",
  "Result 8:0",
  "input: 9/24/11",
  "output: Atlético de Madrid",
  "Result 5:0",
  "input: 9/24/11",
  "output: Atlético de Madrid",
  "Result 5:0",
  "input: 9/24/11",
  "output: Atlético de Madrid",
  "Result 5:0",
  "input: 9/28/11",
  "output: BATE Borisov",
  "Result 0:5",
  "input: 9/28/11",
  "output: BATE Borisov",
  "Result 0:5",
  "input: 10/15/11",
  "output: Racing Santander",
  "Result 3:0",
  "input: 10/15/11",
  "output: Racing Santander",
  "Result 3:0",
  "input: 10/29/11",
  "output: RCD Mallorca",
  "Result 5:0",
  "input: 10/29/11",
  "output: RCD Mallorca",
  "Result 5:0",
  "input: 10/29/11",
  "output: RCD Mallorca",
  "Result 5:0",
  "input: 11/1/11",
  "output: FC Viktoria Plzen",
  "Result 0:4",
  "input: 11/1/11",
  "output: FC Viktoria Plzen",
  "Result 0:4",
  "input: 11/1/11",
  "output: FC Viktoria Plzen",
  "Result 0:4",
  "input: 11/6/11",
  "output: Athletic Bilbao",
  "Result 2:2",
  "input: 11/19/11",
  "output: Real Zaragoza",
  "Result 4:0",
  "input: 11/23/11",
  "output: AC Milan",
  "Result 2:3",
  "input: 11/29/11",
  "output: Rayo Vallecano",
  "Result 4:0",
  "input: 12/3/11",
  "output: Levante UD",
  "Result 5:0",
  "input: 12/18/11",
  "output: Santos FC",
  "Result 0:4",
  "input: 12/18/11",
  "output: Santos FC",
  "Result 0:4",
  "input: 1/4/12",
  "output: CA Osasuna",
  "Result 4:0",
  "input: 1/4/12",
  "output: CA Osasuna",
  "Result 4:0",
  "input: 1/15/12",
  "output: Real Betis Balompié",
  "Result 4:2",
  "input: 1/15/12",
  "output: Real Betis Balompié",
  "Result 4:2",
  "input: 1/22/12",
  "output: Málaga CF",
  "Result 1:4",
  "input: 1/22/12",
  "output: Málaga CF",
  "Result 1:4",
  "input: 1/22/12",
  "output: Málaga CF",
  "Result 1:4",
  "input: 2/4/12",
  "output: Real Sociedad",
  "Result 2:1",
  "input: 2/14/12",
  "output: Bayer 04 Leverkusen",
  "Result 1:3",
  "input: 2/19/12",
  "output: Valencia CF",
  "Result 5:1",
  "input: 2/19/12",
  "output: Valencia CF",
  "Result 5:1",
  "input: 2/19/12",
  "output: Valencia CF",
  "Result 5:1",
  "input: 2/19/12",
  "output: Valencia CF",
  "Result 5:1",
  "input: 2/26/12",
  "output: Atlético de Madrid",
  "Result 1:2",
  "input: 3/7/12",
  "output: Bayer 04 Leverkusen",
  "Result 7:1",
  "input: 3/7/12",
  "output: Bayer 04 Leverkusen",
  "Result 7:1",
  "input: 3/7/12",
  "output: Bayer 04 Leverkusen",
  "Result 7:1",
  "input: 3/7/12",
  "output: Bayer 04 Leverkusen",
  "Result 7:1",
  "input: 3/7/12",
  "output: Bayer 04 Leverkusen",
  "Result 7:1",
  "input: 3/11/12",
  "output: Racing Santander",
  "Result 0:2",
  "input: 3/11/12",
  "output: Racing Santander",
  "Result 0:2",
  "input: 3/17/12",
  "output: Sevilla FC",
  "Result 0:2",
  "input: 3/20/12",
  "output: Granada CF",
  "Result 5:3",
  "input: 3/20/12",
  "output: Granada CF",
  "Result 5:3",
  "input: 3/20/12",
  "output: Granada CF",
  "Result 5:3",
  "input: 3/24/12",
  "output: RCD Mallorca",
  "Result 0:2",
  "input: 3/31/12",
  "output: Athletic Bilbao",
  "Result 2:0",
  "input: 4/3/12",
  "output: AC Milan",
  "Result 3:1",
  "input: 4/3/12",
  "output: AC Milan",
  "Result 3:1",
  "input: 4/7/12",
  "output: Real Zaragoza",
  "Result 1:4",
  "input: 4/7/12",
  "output: Real Zaragoza",
  "Result 1:4",
  "input: 4/10/12",
  "output: Getafe CF",
  "Result 4:0",
  "input: 4/14/12",
  "output: Levante UD",
  "Result 1:2",
  "input: 4/14/12",
  "output: Levante UD",
  "Result 1:2",
  "input: 4/29/12",
  "output: Rayo Vallecano",
  "Result 0:7",
  "input: 4/29/12",
  "output: Rayo Vallecano",
  "Result 0:7",
  "input: 5/2/12",
  "output: Málaga CF",
  "Result 4:1",
  "input: 5/2/12",
  "output: Málaga CF",
  "Result 4:1",
  "input: 5/2/12",
  "output: Málaga CF",
  "Result 4:1",
  "input: 5/5/12",
  "output: RCD Espanyol Barcelona",
  "Result 4:0",
  "input: 5/5/12",
  "output: RCD Espanyol Barcelona",
  "Result 4:0",
  "input: 5/5/12",
  "output: RCD Espanyol Barcelona",
  "Result 4:0",
  "input: 5/5/12",
  "output: RCD Espanyol Barcelona",
  "Result 4:0",
  "input: 5/25/12",
  "output: Athletic Bilbao",
  "Result 3:0",
  "input: 8/19/12",
  "output: Real Sociedad",
  "Result 5:1",
  "input: 8/19/12",
  "output: Real Sociedad",
  "Result 5:1",
  "input: 8/23/12",
  "output: Real Madrid",
  "Result 3:2",
  "input: 8/26/12",
  "output: CA Osasuna",
  "Result 1:2",
  "input: 8/26/12",
  "output: CA Osasuna",
  "Result 1:2",
  "input: 8/29/12",
  "output: Real Madrid",
  "Result 2:1",
  "input: 9/15/12",
  "output: Getafe CF",
  "Result 1:4",
  "input: 9/15/12",
  "output: Getafe CF",
  "Result 1:4",
  "input: 9/19/12",
  "output: Spartak Moscow",
  "Result 3:2",
  "input: 9/19/12",
  "output: Spartak Moscow",
  "Result 3:2",
  "input: 10/7/12",
  "output: Real Madrid",
  "Result 2:2",
  "input: 10/7/12",
  "output: Real Madrid",
  "Result 2:2",
  "input: 10/20/12",
  "output: Deportivo de La Coruña",
  "Result 4:5",
  "input: 10/20/12",
  "output: Deportivo de La Coruña",
  "Result 4:5",
  "input: 10/20/12",
  "output: Deportivo de La Coruña",
  "Result 4:5",
  "input: 10/27/12",
  "output: Rayo Vallecano",
  "Result 0:5",
  "input: 10/27/12",
  "output: Rayo Vallecano",
  "Result 0:5",
  "input: 11/7/12",
  "output: Celtic FC",
  "Result 2:1",
  "input: 11/11/12",
  "output: RCD Mallorca",
  "Result 2:4",
  "input: 11/11/12",
  "output: RCD Mallorca",
  "Result 2:4",
  "input: 11/17/12",
  "output: Real Zaragoza",
  "Result 3:1",
  "input: 11/17/12",
  "output: Real Zaragoza",
  "Result 3:1",
  "input: 11/20/12",
  "output: Spartak Moscow",
  "Result 0:3",
  "input: 11/20/12",
  "output: Spartak Moscow",
  "Result 0:3",
  "input: 11/25/12",
  "output: Levante UD",
  "Result 0:4",
  "input: 11/25/12",
  "output: Levante UD",
  "Result 0:4",
  "input: 12/1/12",
  "output: Athletic Bilbao",
  "Result 5:1",
  "input: 12/1/12",
  "output: Athletic Bilbao",
  "Result 5:1",
  "input: 12/9/12",
  "output: Real Betis Balompié",
  "Result 1:2",
  "input: 12/9/12",
  "output: Real Betis Balompié",
  "Result 1:2",
  "input: 12/12/12",
  "output: Córdoba CF",
  "Result 0:2",
  "input: 12/12/12",
  "output: Córdoba CF",
  "Result 0:2",
  "input: 12/16/12",
  "output: Atlético de Madrid",
  "Result 4:1",
  "input: 12/16/12",
  "output: Atlético de Madrid",
  "Result 4:1",
  "input: 12/22/12",
  "output: Real Valladolid CF",
  "Result 1:3",
  "input: 1/6/13",
  "output: RCD Espanyol Barcelona",
  "Result 4:0",
  "input: 1/13/13",
  "output: Málaga CF",
  "Result 1:3",
  "input: 1/16/13",
  "output: Málaga CF",
  "Result 2:2",
  "input: 1/19/13",
  "output: Real Sociedad",
  "Result 3:2",
  "input: 1/24/13",
  "output: Málaga CF",
  "Result 2:4",
  "input: 1/27/13",
  "output: CA Osasuna",
  "Result 5:1",
  "input: 1/27/13",
  "output: CA Osasuna",
  "Result 5:1",
  "input: 1/27/13",
  "output: CA Osasuna",
  "Result 5:1",
  "input: 1/27/13",
  "output: CA Osasuna",
  "Result 5:1",
  "input: 2/3/13",
  "output: Valencia CF",
  "Result 1:1",
  "input: 2/10/13",
  "output: Getafe CF",
  "Result 6:1",
  "input: 2/16/13",
  "output: Granada CF",
  "Result 1:2",
  "input: 2/16/13",
  "output: Granada CF",
  "Result 1:2",
  "input: 2/23/13",
  "output: Sevilla FC",
  "Result 2:1",
  "input: 3/2/13",
  "output: Real Madrid",
  "Result 2:1",
  "input: 3/9/13",
  "output: Deportivo de La Coruña",
  "Result 2:0",
  "input: 3/12/13",
  "output: AC Milan",
  "Result 4:0",
  "input: 3/12/13",
  "output: AC Milan",
  "Result 4:0",
  "input: 3/17/13",
  "output: Rayo Vallecano",
  "Result 3:1",
  "input: 3/17/13",
  "output: Rayo Vallecano",
  "Result 3:1",
  "input: 3/30/13",
  "output: Celta de Vigo",
  "Result 2:2",
  "input: 4/2/13",
  "output: Paris Saint-Germain",
  "Result 2:2",
  "input: 4/27/13",
  "output: Athletic Bilbao",
  "Result 2:2",
  "input: 5/5/13",
  "output: Real Betis Balompié",
  "Result 4:2",
  "input: 5/5/13",
  "output: Real Betis Balompié",
  "Result 4:2",
  "input: 8/18/13",
  "output: Levante UD",
  "Result 7:0",
  "input: 8/18/13",
  "output: Levante UD",
  "Result 7:0",
  "input: 9/1/13",
  "output: Valencia CF",
  "Result 2:3",
  "input: 9/1/13",
  "output: Valencia CF",
  "Result 2:3",
  "input: 9/1/13",
  "output: Valencia CF",
  "Result 2:3",
  "input: 9/14/13",
  "output: Sevilla FC",
  "Result 3:2",
  "input: 9/18/13",
  "output: Ajax Amsterdam",
  "Result 4:0",
  "input: 9/18/13",
  "output: Ajax Amsterdam",
  "Result 4:0",
  "input: 9/18/13",
  "output: Ajax Amsterdam",
  "Result 4:0",
  "input: 9/24/13",
  "output: Real Sociedad",
  "Result 4:1",
  "input: 9/28/13",
  "output: UD Almería",
  "Result 0:2",
  "input: 10/22/13",
  "output: AC Milan",
  "Result 1:1",
  "input: 11/6/13",
  "output: AC Milan",
  "Result 3:1",
  "input: 11/6/13",
  "output: AC Milan",
  "Result 3:1",
  "input: 1/8/14",
  "output: Getafe CF",
  "Result 4:0",
  "input: 1/8/14",
  "output: Getafe CF",
  "Result 4:0",
  "input: 1/16/14",
  "output: Getafe CF",
  "Result 0:2",
  "input: 1/16/14",
  "output: Getafe CF",
  "Result 0:2",
  "input: 2/1/14",
  "output: Valencia CF",
  "Result 2:3",
  "input: 2/9/14",
  "output: Sevilla FC",
  "Result 1:4",
  "input: 2/9/14",
  "output: Sevilla FC",
  "Result 1:4",
  "input: 2/12/14",
  "output: Real Sociedad",
  "Result 1:1",
  "input: 2/15/14",
  "output: Rayo Vallecano",
  "Result 6:0",
  "input: 2/15/14",
  "output: Rayo Vallecano",
  "Result 6:0",
  "input: 2/18/14",
  "output: Manchester City",
  "Result 0:2",
  "input: 2/22/14",
  "output: Real Sociedad",
  "Result 3:1",
  "input: 3/2/14",
  "output: UD Almería",
  "Result 4:1",
  "input: 3/12/14",
  "output: Manchester City",
  "Result 2:1",
  "input: 3/16/14",
  "output: CA Osasuna",
  "Result 7:0",
  "input: 3/16/14",
  "output: CA Osasuna",
  "Result 7:0",
  "input: 3/16/14",
  "output: CA Osasuna",
  "Result 7:0",
  "input: 3/23/14",
  "output: Real Madrid",
  "Result 3:4",
  "input: 3/23/14",
  "output: Real Madrid",
  "Result 3:4",
  "input: 3/23/14",
  "output: Real Madrid",
  "Result 3:4",
  "input: 3/26/14",
  "output: Celta de Vigo",
  "Result 3:0",
  "input: 3/29/14",
  "output: RCD Espanyol Barcelona",
  "Result 0:1",
  "input: 4/5/14",
  "output: Real Betis Balompié",
  "Result 3:1",
  "input: 4/5/14",
  "output: Real Betis Balompié",
  "Result 3:1",
  "input: 4/20/14",
  "output: Athletic Bilbao",
  "Result 2:1",
  "input: 4/27/14",
  "output: Villarreal CF",
  "Result 2:3",
  "input: 5/3/14",
  "output: Getafe CF",
  "Result 2:2",
  "input: 8/24/14",
  "output: Elche CF",
  "Result 3:0",
  "input: 8/24/14",
  "output: Elche CF",
  "Result 3:0",
  "input: 9/21/14",
  "output: Levante UD",
  "Result 0:5",
  "input: 9/27/14",
  "output: Granada CF",
  "Result 6:0",
  "input: 9/27/14",
  "output: Granada CF",
  "Result 6:0",
  "input: 9/30/14",
  "output: Paris Saint-Germain",
  "Result 3:2",
  "input: 10/4/14",
  "output: Rayo Vallecano",
  "Result 0:2",
  "input: 10/18/14",
  "output: SD Eibar",
  "Result 3:0",
  "input: 10/21/14",
  "output: Ajax Amsterdam",
  "Result 3:1",
  "input: 11/5/14",
  "output: Ajax Amsterdam",
  "Result 0:2",
  "input: 11/5/14",
  "output: Ajax Amsterdam",
  "Result 0:2",
  "input: 11/22/14",
  "output: Sevilla FC",
  "Result 5:1",
  "input: 11/22/14",
  "output: Sevilla FC",
  "Result 5:1",
  "input: 11/22/14",
  "output: Sevilla FC",
  "Result 5:1",
  "input: 11/25/14",
  "output: APOEL Nicosia",
  "Result 0:4",
  "input: 11/25/14",
  "output: APOEL Nicosia",
  "Result 0:4",
  "input: 11/25/14",
  "output: APOEL Nicosia",
  "Result 0:4",
  "input: 12/7/14",
  "output: RCD Espanyol Barcelona",
  "Result 5:1",
  "input: 12/7/14",
  "output: RCD Espanyol Barcelona",
  "Result 5:1",
  "input: 12/7/14",
  "output: RCD Espanyol Barcelona",
  "Result 5:1",
  "input: 12/10/14",
  "output: Paris Saint-Germain",
  "Result 3:1",
  "input: 12/20/14",
  "output: Córdoba CF",
  "Result 5:0",
  "input: 12/20/14",
  "output: Córdoba CF",
  "Result 5:0",
  "input: 1/8/15",
  "output: Elche CF",
  "Result 5:0",
  "input: 1/11/15",
  "output: Atlético de Madrid",
  "Result 3:1",
  "input: 1/18/15",
  "output: Deportivo de La Coruña",
  "Result 0:4",
  "input: 1/18/15",
  "output: Deportivo de La Coruña",
  "Result 0:4",
  "input: 1/18/15",
  "output: Deportivo de La Coruña",
  "Result 0:4",
  "input: 1/21/15",
  "output: Atlético de Madrid",
  "Result 1:0",
  "input: 1/24/15",
  "output: Elche CF",
  "Result 0:6",
  "input: 1/24/15",
  "output: Elche CF",
  "Result 0:6",
  "input: 2/1/15",
  "output: Villarreal CF",
  "Result 3:2",
  "input: 2/8/15",
  "output: Athletic Bilbao",
  "Result 2:5",
  "input: 2/11/15",
  "output: Villarreal CF",
  "Result 3:1",
  "input: 2/15/15",
  "output: Levante UD",
  "Result 5:0",
  "input: 2/15/15",
  "output: Levante UD",
  "Result 5:0",
  "input: 2/15/15",
  "output: Levante UD",
  "Result 5:0",
  "input: 2/28/15",
  "output: Granada CF",
  "Result 1:3",
  "input: 3/8/15",
  "output: Rayo Vallecano",
  "Result 6:1",
  "input: 3/8/15",
  "output: Rayo Vallecano",
  "Result 6:1",
  "input: 3/8/15",
  "output: Rayo Vallecano",
  "Result 6:1",
  "input: 3/14/15",
  "output: SD Eibar",
  "Result 0:2",
  "input: 3/14/15",
  "output: SD Eibar",
  "Result 0:2",
  "input: 4/8/15",
  "output: UD Almería",
  "Result 4:0",
  "input: 4/11/15",
  "output: Sevilla FC",
  "Result 2:2",
  "input: 4/18/15",
  "output: Valencia CF",
  "Result 2:0",
  "input: 4/25/15",
  "output: RCD Espanyol Barcelona",
  "Result 0:2",
  "input: 4/28/15",
  "output: Getafe CF",
  "Result 6:0",
  "input: 4/28/15",
  "output: Getafe CF",
  "Result 6:0",
  "input: 5/2/15",
  "output: Córdoba CF",
  "Result 0:8",
  "input: 5/2/15",
  "output: Córdoba CF",
  "Result 0:8",
  "input: 5/6/15",
  "output: Bayern Munich",
  "Result 3:0",
  "input: 5/6/15",
  "output: Bayern Munich",
  "Result 3:0",
  "input: 5/17/15",
  "output: Atlético de Madrid",
  "Result 0:1",
  "input: 5/23/15",
  "output: Deportivo de La Coruña",
  "Result 2:2",
  "input: 5/23/15",
  "output: Deportivo de La Coruña",
  "Result 2:2",
  "input: 5/30/15",
  "output: Athletic Bilbao",
  "Result 1:3",
  "input: 5/30/15",
  "output: Athletic Bilbao",
  "Result 1:3",
  "input: 8/11/15",
  "output: Sevilla FC",
  "Result 5:4",
  "input: 8/11/15",
  "output: Sevilla FC",
  "Result 5:4",
  "input: 8/17/15",
  "output: Athletic Bilbao",
  "Result 1:1",
  "input: 9/12/15",
  "output: Atlético de Madrid",
  "Result 1:2",
  "input: 9/20/15",
  "output: Levante UD",
  "Result 4:1",
  "input: 9/20/15",
  "output: Levante UD",
  "Result 4:1",
  "input: 11/24/15",
  "output: AS Roma",
  "Result 6:1",
  "input: 11/24/15",
  "output: AS Roma",
  "Result 6:1",
  "input: 11/28/15",
  "output: Real Sociedad",
  "Result 4:0",
  "input: 12/9/15",
  "output: Bayer 04 Leverkusen",
  "Result 1:1",
  "input: ",
  "output: ",
]

ask = input("Question: ")
response = model.generate_content(ask)
print(response.text)